### ISSUE TITLE
Set default CPU shares value to non-None object

### ISSUE THREAD

**Issue by captainsafia** [jupyter/tmpnb#156]
With the addition of `cpu_shares` to the container configuration in pull request #154, the default value set for `cpu_shares` in `orchestrate.py` is set to None which cascades down to the `int` call in `create_notebook_server` and makes things go kablooey.

```
Traceback (most recent call last):
  File "orchestrate.py", line 289, in <module>
    main()
  File "orchestrate.py", line 269, in main
    ioloop.run_sync(pool.heartbeat)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 418, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 189, in heartbeat
    yield tasks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 464, in callback
    result_list = [i.result() for i in children]
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 227, in _launch_container
    container_config=self.container_config)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 175, in wrapper
    yielded = next(result)
  File "/srv/tmpnb/dockworker.py", line 110, in create_notebook_server
    cpu_shares=int(container_config.cpu_shares),
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by captainsafia** [comment]
Conversely, I guess you can also not cast `container_config.cpu_shares` into an integer. 

@rgbkrk, any specific reason you did this? From what I've poked through docker-py's `create_container` function doesn't require an integer argument.

**Comment by rgbkrk** [comment]
When cpu-shares was being specified (at least on Docker 1.6), Docker/go was reporting back this error:

```
[E 150826 07:52:08 dockworker:183] Encountered a Docker error with method (5 retries remain): 400 Client Error: Bad Request ("json: cannot unmarshal string into Go value of type int64")
```

This then broke things for the non-specified case.

**Comment by captainsafia** [comment]
@rgbkrk — Hm. Yeah. I was experiencing this issue on Docker 1.7. Would be interesting to see if there is anything else in the code that might have problems across Docker versions. 

Thanks for the fix!
