### ISSUE TITLE
Failure getting host port when starting tmpnb

### ISSUE THREAD

**Issue by parente** [jupyter/tmpnb#175]
Run command:

```
docker run -d \
		--name=tmpnb \
		--net=host \
		-e CONFIGPROXY_AUTH_TOKEN=$(TOKEN) \
		-v /var/run/docker.sock:/docker.sock \
		$(TMPNB_IMAGE) \
		python orchestrate.py --image='$(NOTEBOOK_IMAGE)' \
			--container_user=jovyan \
			--container_port=34000 \
			--command='/opt/conda/bin/ipython notebook \
				--NotebookApp.base_url={base_path} \
				--ip=127.0.0.1 \
				--port={port} \
				--NotebookApp.trust_xheaders=True'
```

Log output:

```
$ docker logs tmpnb
[W 150924 03:09:25 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:25 dockworker:126] Created container 9620a4065fd95194971d6c6277222b7bba522ea1f8e937daa4158ddd2476b628
[W 150924 03:09:25 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:25 dockworker:126] Created container 7e8507d869a1fd57e1a7651bde5eb481699b92f21208a8fcff3f19c03b344bd1
[W 150924 03:09:25 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:25 dockworker:126] Created container bd76b8ebdbd15ebde22cd0211646a84ee1a9daa25f131193663577cd92e31a64
[W 150924 03:09:25 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:25 dockworker:126] Created container 44dd3eb8c9bec5e83077e8b6cf3e724cb60fa084db882d46773cab72f55b991d
[W 150924 03:09:25 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:25 dockworker:126] Created container 26e80392ad272872899cb38277131d30d4a9017b85ed2a8b8e962a73efa98a84
[W 150924 03:09:26 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:26 dockworker:126] Created container 709e82fb9d2064badfb41932ad873ca91bec7dec363e9e7fc0ab15f6bf6529dd
[W 150924 03:09:26 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:26 dockworker:126] Created container 419ec580fa9268045e69fb192ac86b89934666cd5a719c7750aec47be37d1a57
[W 150924 03:09:26 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:26 dockworker:126] Created container 3c3e03001e9398099ba48da3ba3590ef41e405cc6596f62f990dfcde9363c381
[W 150924 03:09:26 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:26 dockworker:126] Created container 538c315cf88db63c9463079a96a56b5e369764dde0f34f425ebb3ca2b5258d43
[W 150924 03:09:26 dockworker:123] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 150924 03:09:26 dockworker:126] Created container 378048be05a9fa8e2c8a95131f9ee4f8f93bfdbe01ed70264ded12629a2423d0
Traceback (most recent call last):
  File "orchestrate.py", line 340, in <module>
    main()
  File "orchestrate.py", line 320, in main
    ioloop.run_sync(pool.heartbeat)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 418, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 189, in heartbeat
    yield tasks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 464, in callback
    result_list = [i.result() for i in children]
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 227, in _launch_container
    container_config=self.container_config)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
    yielded = self.gen.send(value)
  File "/srv/tmpnb/dockworker.py", line 139, in create_notebook_server
    host_port = container_network[0]['HostPort']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by parente** [comment]
Doh! Ignore. Mixup of my host_network options and regular usage options.

**Comment by mcgeeco** [comment]
I'm getting the same error when trying to use the commands in the 'Quick Start' section of the ReadMe. Would you be able to elaborate?

**Comment by parente** [comment]
I believe I was getting the above while working on a custom branch of tmpnb, experimenting with the feature of running the notebook containers on the host network as well for PR #172. IIRC, the problem was a bug in my implementation for the PR.

**Comment by mcgeeco** [comment]
Hmmm. I must have something misconfigured somewhere. Thanks!
