### ISSUE TITLE
Error starting tmpnb containter when following 'Quick Start' instructions

### ISSUE THREAD

**Issue by mcgeeco** [jupyter/tmpnb#190]
Hi. I used the commands in the Quick Start instructions but the tmpnb keeps failing to start up properly with this error in the logs:
```
[I 151210 13:51:18 spawnpool:131] Performing initial pool cleanup
[W 151210 13:51:18 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:18 dockworker:144] Created container af8b15bf8ab7bb771fc45e00bd3c8759c06ae292848b606d4c4fe0a31b2a344c
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container bdbb39d8e4f8aa1546f5a7835a19293f8143cb99d8f5d0069ab076a3e6ccb90d
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container 539aa05439ef123281f177cfec1e835eac9f60f895567223ddb33fbe6d770b02
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container a686ec99843b106ab03195fe61fa7a1fdbed6abb4f5cd619fc9d0a99bcf41615
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container d2ff9e463d33433c1dbf9b9092105b60d42efb076c245847cd9e749bb156a034
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container aca140d67c859c76358740556a963e471ab8a12ac137eb1cc6cd2e5d43f65835
[W 151210 13:51:19 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:19 dockworker:144] Created container bc0654b0ff8c71681a8852043e31d553a79e5f0abae21735ee4588682b9aa420
[W 151210 13:51:20 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:20 dockworker:144] Created container 032e4f05bd3534331d8f017be0a7937b7f89ea5b3259e760ef4b74654de7be68
[W 151210 13:51:20 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:20 dockworker:144] Created container 37c495c8f338b33403d087339d7b504d2497c818f1cdf566351615a81c2bb531
[W 151210 13:51:20 dockworker:141] [u'Your kernel does not support swap limit capabilities, memory limited without swap.']
[I 151210 13:51:20 dockworker:144] Created container bd70ad9e62ea1821988a59588fc5a23d228ae42a9a2bfe0d300aaa054d40fe3f
Traceback (most recent call last):
  File "orchestrate.py", line 372, in <module>
    main()
  File "orchestrate.py", line 352, in main
    ioloop.run_sync(pool.heartbeat)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 418, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 202, in heartbeat
    yield tasks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 464, in callback
    result_list = [i.result() for i in children]
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 240, in _launch_container
    container_config=self.container_config)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
    yielded = self.gen.send(value)
  File "/srv/tmpnb/dockworker.py", line 158, in create_notebook_server
    host_port = container_network[0]['HostPort']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Docker version 1.9.1, build a34a1d5 on Ubuntu 15.10.

Any ideas?

**Comment by ksindi** [comment]
Have the same issue.

**Comment by captainsafia** [comment]
Thanks for opening up this issue @mcgeeco and for commenting @ksindi. I'll attempt to reproduce and debug.

Just to confirm, the command sequence you are running is the below?

```
docker pull jupyter/minimal
export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb
```

**Comment by ksindi** [comment]
Correct. Thanks @captainsafia !

**Comment by mcgeeco** [comment]
That's right. Let me know if I can help with anything else - (I'm having a go at fixing it myself but I'm new to Tornado and just starting to get my head around Docker properly).

**Comment by parente** [comment]
Hmm. That minimal image is deprecated on Docker Hub:

https://hub.docker.com/r/jupyter/minimal/

and no longer the basis for the demo image used on tmpnb.org either. Maybe a long shot, but perhaps the code base here has changed and is no longer compatible? What happens if you swap in `jupyter/minimal-notebook instead`?

**Comment by captainsafia** [comment]
@parente: Neat recommendation. I tried it and it didn't appear to work for this specific issue. None the less, it's good to note that we should update the README to reflect that the new image should be used.

I didn't really get a chance to look into it last night but I'll be able to now.

**Comment by captainsafia** [comment]
@mcgeeco: Can you try running the following instead of the last command:

```
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='jupyter/minimal-notebook' --command="ipython notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port}"
```
This takes into account the image that @parente recommended using just to be safe and a test to see whether some changes that were recently introduced might be causing this problem.

**Comment by ksindi** [comment]
Thanks @captainsafia! That worked for me. FYI I used `jupyter/minimal-notebook`.

**Comment by parente** [comment]
@ksindi Be careful: that `ipython notebook` command has the container running as root. Be sure to check this part of the README if you plan to stick with the minimal-notebook image: https://github.com/jupyter/tmpnb#using-jupyterdocker-stacks-images.

**Comment by ksindi** [comment]
Noted. Thanks @parente!

**Comment by mcgeeco** [comment]
Hi @captainsafia , sorry for the delay. Yes that new line works, except that I had to manually pull the jupyter/minimal-notebook:latest image.

**Comment by betatim** [comment]
@captainsafia you need to update the default image name in [orchestrate.py](https://github.com/jupyter/tmpnb/blob/master/orchestrate.py#L254) as well. Otherwise you get the old one when not explicitly specifying one on the command line.

**Comment by captainsafia** [comment]
@betatim — Oh my goodness! Thank you for catching that! Fix PR incoming.

**Comment by mcgeeco** [comment]
Thanks, all. Really cool project.

**Comment by EmptyCrown** [comment]
I'm getting this error with the updated `jupyter/minimal-notebook`. With the plane `jupyter/tmpnb` notebook, everything looks fine. However, I'm adding a small customization on top using `jupyter_notebook_config.py`. It has the following contents
```python
c.NotebookApp.tornado_settings = {
    "headers": {
        "Content-Security-Policy": "frame-ancestors self http://localhost:9000; report-uri /api/security/csp-report"
    }
}
c.NotebookApp.allow_origin = '*'
```
Then, my Dockerfile is 
```
FROM jupyter/tmpnb
ADD jupyter_notebook_config.py /etc/jupyter_notebook_config.py
```
After building and running with
```
CONFIGPROXY_AUTH_TOKEN=$TOKEN python3 tmpnb/orchestrate.py --image=myjupyter --command='jupyter notebook --no-browser --port {port} --ip=0.0.0.0 --NotebookApp.config_file=/etc/jupyter_notebook_config.py --NotebookApp.base_url=/{base_path} --NotebookApp.port_retries=0' --container-user=jovyan
```
I got the same errors. Does anyone have any ideas? Thanks!
```
Traceback (most recent call last):
  File "orchestrate.py", line 509, in <module>
    main()
  File "orchestrate.py", line 482, in main
    ioloop.run_sync(pool.heartbeat)
  File "/usr/local/lib/python3.4/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/tmpnb/spawnpool.py", line 246, in heartbeat
    yield tasks
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 789, in callback
    result_list.append(f.result())
  File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/tmpnb/spawnpool.py", line 284, in _launch_container
    container_config=self.container_config)
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/srv/tmpnb/dockworker.py", line 212, in create_notebook_server
    host_port = container_network[0]['HostPort']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rgbkrk** [comment]
No one is currently supporting tmpnb at this point. It's highly recommended you switch to using JupyterHub, possibly with [BinderHub](https://binderhub.readthedocs.io/en/latest/).
