### ISSUE TITLE
Container name already in use by another container

### ISSUE THREAD

**Issue by betatim** [jupyter/tmpnb#200]
Tried to setup `tmpnb` and after the fix of #190 (explicitly stating `--image jupyter/minimal-notebook`) get a running container pool, but get a 500 when visiting http://172.xx.65.106:9999

This is the output of `docker logs tmpnb`:
```
[I 160107 16:25:39 web:1811] 304 GET / (128.141.130.161) 4.46ms
[I 160107 16:25:39 orchestrate:128] Allocated [user/tRn30yKmsodj] from the pool.
[I 160107 16:25:39 web:1811] 302 GET /spawn/ (128.141.130.161) 0.53ms
[I 160107 16:25:39 web:1811] 200 GET /user/tRn30yKmsodj/tree (128.141.130.161) 1.72ms
[I 160107 16:25:39 spawnpool:108] Releasing container [PooledContainer(id=u'8e02e1cf2cce6804c3ddf984078e415cea5e221f6e6bba7e10aa4207ed86ea2e', path='user/KLZbIqGHZvRe')].
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (5 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (4 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (3 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (2 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (1 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 dockworker:230] Encountered a Docker error with method (0 retries remain): 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 web:1407] Uncaught exception GET /spawn/user/tRn30yKmsodj/tree (128.141.130.161)
    HTTPServerRequest(protocol='http', host='172.99.65.106:9999', method='GET', uri='/spawn/user/tRn30yKmsodj/tree', version='HTTP/1.1', remote_ip='128.141.130.161', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '172.99.65.106:9999', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.23 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://172.99.65.106:9999/user/tRn30yKmsodj/tree', 'Cookie': '_gat=1; _ga=GA1.1.1895995436.1452182692', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1334, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "orchestrate.py", line 121, in get
        yield self.pool.adhoc(user)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/spawnpool.py", line 97, in adhoc
        launched = yield self._launch_container(user=user, enpool=False)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/spawnpool.py", line 261, in _launch_container
        container_config=self.container_config)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 157, in create_notebook_server
        name=container_name)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 233, in _with_retries
        result = yield self._with_retries(fn, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 233, in _with_retries
        result = yield self._with_retries(fn, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 233, in _with_retries
        result = yield self._with_retries(fn, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 233, in _with_retries
        result = yield self._with_retries(fn, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 233, in _with_retries
        result = yield self._with_retries(fn, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/srv/tmpnb/dockworker.py", line 236, in _with_retries
        raise e
    APIError: 409 Client Error: Conflict ("Conflict. The name "tmp.jupyterminimal-notebook.tRn30yKmsodj" is already in use by container 35266dbb4a7c. You have to remove (or rename) that container to be able to reuse that name.")
[E 160107 16:25:40 web:1811] 500 GET /spawn/user/tRn30yKmsodj/tree (128.141.130.161) 282.27ms
```

Then my browser ends up on http://172.xx.65.106:9999/spawn/user/tRn30yKmsodj/tree. It seems like it allocates a container to me, but then tries to start one with the same name?? If I try and surf directly to something like http://172.xx.65.106:9999/user/ThisIsUniqueForSure/ the error message is the same (as in it trips up trying to create the container again after creating it the first time).

This is on a docker-swarm with one node. Ran these commands:

```
$ docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
$ docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='jupyter/minimal-notebook'
```

**Comment by betatim** [comment]
I did some poking around (O.M.G. pdb in a world of async is ~useless, what do people use?). I set a breakpoint at the start of `Spawnhandler.get`, started everything up and waited.

When you first visit http://mytmpnb:9999 you eventually end up in `SpawnHandler.get` with `path=None`, which redirects you ```Redirecting [/spawn/] -> [/user/7IOA6q7Vwm1C/tree].```. At this point I pressed `c`. The breakpoint triggers again but with `path=/user/7IOA6q7Vwm1C/tree`, for which `is-user_path()` is True. Now we call `acquire(7IOA6q7Vwm1C)`, which scraps a container and then tries to create one with the given name. That is already in use, and we end up with the above exception.

What I don't understand is why the redirect results in us being back in `SpawnHandler`. As the redirect is to `/user/...` my guess would have been `LoadingHandler`. Trying to acquire a new container after just being assigned one definitely seems like a bug.

**Comment by betatim** [comment]
If you step into `self.redirect('/user/7IOA6q7Vwm1C/tree', False)` then it sets the Location header to:

```
self.set_header("Location", urlparse.urljoin(utf8(self.request.uri),
  	                                                     utf8(url)))
```
which is `/spawn/user/...`. Wat? Why does tornado concatenate these two?

**Comment by betatim** [comment]
The last comment is probably a red herring.

The failure is in [spawnpool's `adhoc()`](https://github.com/jupyter/tmpnb/blob/master/spawnpool.py#L89) which is being called from `SpawnHandler`. It releases a container and then tries to create a new one for the given user name. However the username was acquired from the list of available containers so when it tries to create the container it fails. I don't understand why we first obtain a container from the pool and then `adhoc` one. Maybe @rgbkrk knows why it was done like this?

**Comment by betatim** [comment]
Sorry for all the noise: PEBCAK. Don't be accessing tmpnb directly but through the configurable-proxy otherwise you keep being sent back to the same place all the time as the proxy can't redirect you to your container if you don't make connections through it. D'oh. Access :8000 not :9999

**Comment by rgbkrk** [comment]
That was some crafty debugging regardless. I have no idea what tools are available for debugging asynchronous Python, maybe @minrk.
