### ISSUE TITLE
running into issues running the proxy

### ISSUE THREAD

**Issue by zunayed** [jupyter/tmpnb#251]
Hi I tried following the quickstart and am failing at the proxy step. I outputted the logs from the failed container below. 

```` bash
zali@dockerub01:~$ sudo docker run -p 0.0.0.0:8002:8000 --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999 
4befe6a3d665f0220f786ab562fd29243e32f5b56f2cfc2b9da0ec285df35b66

zali@dockerub01:~$ sudo docker logs proxy
20:11:43.168 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:9999
20:11:43.171 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8001
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

my docker version
```
zali@dockerub01:~$ docker --version
Docker version 1.12.1, build 23cf638
```

**Comment by vsakharuk** [comment]
Same issue here, anyone?

**Comment by parente** [comment]
Do you have another container / service running that is using port 8001? When you're using `--net=host` you have to check for port conflicts on the host system. `netstat -a | grep 8001` might help as can `docker ps -a`.

**Comment by vsakharuk** [comment]
@parente, Worked for me, thank you!
